[package]
name = "zigate"
version = "0.1.0"
authors = ["lucas-str <lucas.sturelle@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytebuffer-rs = "0.3"
env_logger = "0.7"
log = "0.4"
rppal = "0.11"
